### ISSUE TITLE
ESLint test generator only works with QUnit

### ISSUE THREAD

**Issue by nucleartide** [ember-cli/ember-cli-eslint#105]
The docs say that things should "Just Work", but that doesn't seem to be the case when I'm using ember-cli-eslint together with ember-cli-mocha. It seems to me like the [default test generator][1] only returns QUnit tests for linting, never Mocha tests.

Using that as an example, I wrote a test generator for Mocha:

```js
var jsStringEscape = require('js-string-escape')
var EmberApp = require('ember-cli/lib/broccoli/ember-app')

function render(errors) {
  if (!errors) return ''
  return errors.map(err => `${err.line}:${err.column} - ${err.message} (${err.ruleId})`).join(jsStringEscape('\n'))
}

function eslintTestGenerator(relativePath, errors) {
  const pass = !errors || errors.length === 0
  const errs = render(errors)
  return `
    import Chai from 'chai'
    import { describe, it } from 'mocha'

    const { assert } = Chai

    describe('${relativePath}', function() {
      it('should pass ESLint', function() {
        assert.ok(${pass}, '${relativePath + ' should pass ESLint.' + jsStringEscape('\n\n' + errs + '\n\n')}')
      })
    })
  `
}

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    eslint: {
      testGenerator: eslintTestGenerator
    }
  })
}
```

I'm not entirely sure how this could be fixed - should the test generator functions be moved to their respective Ember addons (ember-cli-qunit and ember-cli-mocha)? This was very, very frustrating to see upon installing ember-cli-mocha.

(Also, the test generator function above requires Node 4+, for those ES6 features.)

[1]: https://github.com/ember-cli/ember-cli-eslint/blob/master/ember-cli-build.js#L25

**Comment by alexlafroscia** [comment]
Which version of `ember-cli` are you using? I know for a fact that they work together, because I work on numerous apps that use `eslint` and `mocha`.

After Ember CLI 2.5.0, the test runner provides the linter function, so it does "just work".  If you're using an older version of the CLI then that, then you have to provide the test function yourself.

**Comment by nucleartide** [comment]
Just tried on a fresh project, see the pic below. Here's the repo: [link](https://github.com/nucleartide/__eslint-test__).

It doesn't bombard me with loads of linting errors like it did in my app 😄 , but it does still generate JSHint test cases for whatever reason.

node version: v4.2.2
npm version: 2.14.7
ember-cli version: 2.7.0
ember-cli-mocha version: 0.10.4
ember-cli-eslint version: 1.7.0

![screenshot 2016-08-12 14 46 05](https://cloud.githubusercontent.com/assets/914228/17633494/8eb7ad3c-609b-11e6-9225-1e20ae506676.png)

**Comment by alexlafroscia** [comment]
Did you also uninstall `ember-cli-jshint`?  It will override the `eslint` config and you'll see that output.  This will be fixed once #91 is pulled in, which will uninstall `jshint` and the config files for it on installation

**Comment by nucleartide** [comment]
Ah, whoops! That is it, I must have been confused by my [commit message](https://github.com/nucleartide/__eslint-test__/commit/7a35f46be6026236b822b2dc7c2e5bd4b891c0d3).

Amazingly, it also works in my current app if I comment out my custom test generator. Maybe yesterday was just a bad day...

Thanks for the help! 😄

**Comment by alexlafroscia** [comment]
Yeah, it looks like [jshint is still in there](https://github.com/nucleartide/__eslint-test__/commit/7a35f46be6026236b822b2dc7c2e5bd4b891c0d3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L32).

Not problem! Happy to. Actually just had this problem at work with a new app, so I recognized the issue.
