### ISSUE TITLE
Mini RFC: Enable "es6" in the default env setting

### ISSUE THREAD

**Issue by BrianSipple** [ember-cli/ember-cli-eslint#116]
I've been using our latest 2.x version in a project that makes use of [`Map`](https://github.com/ember-cli/ember-cli-eslint/blob/master/index.js#L74), and with the current default config, ESLint will report an error after parsing `Map` as an undefined variable. [Exactly like this](https://github.com/eslint/eslint/issues/5674).

It turns out we could support `Map` (and I'd imagine `Set`, though I haven't confirmed it) just by [adding `es6: true` to the `env` setting](https://github.com/eslint/eslint/issues/5674#issuecomment-201284756) of the config hash. Is there any reason not to do this? I can PR a quick change if not.

**Comment by Turbo87** [comment]
`Map` and `Set` are not ES6 syntax features that are transpiled by Babel, so to use them you either need native Browser support or a polyfill. The default Ember CLI build doesn't have a polyfill and the Ember compatibility down to IE9 means that we can't trust browsers to have native support.

**Comment by BrianSipple** [comment]
@Turbo87 👍 Thanks for putting those pieces together for me.
