### ISSUE TITLE
Installation instructions don't match published versions

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-cli-eslint#117]
The installation instructions on the README mention the following commands

```
ember install ember-cli-eslint@3
ember install ember-cli-eslint@2
```

however, neither of these packages actually exist on NPM; `1.8.0` is the latest.  Are those versions coming soon  or what?  It might be confusing to people that those commands don't "just work" right now.

**Comment by Turbo87** [comment]
@alexlafroscia indeed, I got a bit ahead of myself there... 😉 

2.0.0 and 3.0.0 were just released, so this should work fine now! 🎉

**Comment by alexlafroscia** [comment]
Woo! Thanks @Turbo87
