### ISSUE TITLE
addons are eslinted when imported

### ISSUE THREAD

**Issue by ezpuzz** [ember-cli/ember-cli-eslint#14]
in my case we are extending the ember-rapid-forms components to be compatible with foundation.
when running `ember serve` initially or `ember test` with the generator in the readme.

I've tried using `// eslint-disable-line` at the end of the import lines, but the imported modules are still linted (and the imports of those modules).

Is there a workaround to disable linting of certain imports? 

Is there a way you could not lint files that were part of an addon?

**Comment by jonathanKingston** [comment]
Are the addon files within vendor, node_modules or bower?

**Comment by ezpuzz** [comment]
node_modules, installed with npm

**Comment by jonathanKingston** [comment]
I'll look at it tomorrow, those files were out of scope before. Thanks for reporting.

**Comment by ezpuzz** [comment]
with the latest beta i can use `**/modules/**` in the `.eslintignore` and that gets rid of errors on the addons.
there is probably a better way though.
also even though no errors are displayed I do get a bunch of newlines being printed during the `Building...` step only when ember-cli-eslint is run.

**Comment by ezpuzz** [comment]
the newlines are really making my CI logs look nasty, any way you could figure out what is causing a bunch of newlines to spit out?

**Comment by jonathanKingston** [comment]
Should be fixed in the latest beta, kick the module and reinstall.
I'll release another version tonight which shouldn't require the aggressive
delete and reinstall.

**Comment by ezpuzz** [comment]
:+1: beta.13 seems to be working nicely

**Comment by bttf** [comment]
I experienced the same issue today after installing the ember liquid-fire add-on. It was only linting the liquid-fire add-on out of my other add-ons. The add-on was installed via `ember install liquid-fire` and was located inside `node_modules`

Adding `**/modules/**` to .eslintignore did fix it; I was also able to reproduce the issue by just creating a new ember project, installing ember-cli-eslint, then liquid-fire and then running `ember build`

**Comment by ezpuzz** [comment]
also I think if `addon.isDevelopingAddon` is set improperly inside the addon it can trigger your parent project to lint the addon.
