### ISSUE TITLE
Migrate all addons 

### ISSUE THREAD

**Issue by aureliosaraiva** [ember-cli/ember-cli-eslint#140]
Is there any initiative to migrate all addons to use eslint?

Also, is there any reason to use eslint: recommend instead of eslint: airbnb?

Sorry, if this was discussed elsewhere, I did not find anything.

**Comment by alexlafroscia** [comment]
> Is there any initiative to migrate all addons to use eslint?

What does "all addons" mean in this instance? Do you mean the default blueprint?

> Also, is there any reason to use eslint: recommend instead of eslint: airbnb?

The Airbnb config is a lot more specific, the ESLint recommendation isn't actually all that strict.

**Comment by aureliosaraiva** [comment]
@alexlafroscia The main question is: Is there any planning to make the blueprint standard?

**Comment by Turbo87** [comment]
> Is there any initiative to migrate all addons to use eslint?

yes, we are planning to drop JSHint and use ESLint by default, but there are some small technical issues that we have to resolve first. if you want to help, feel free to check out https://github.com/ember-cli/ember-cli/issues/6269 and help us resolve it.

**Comment by Turbo87** [comment]
the tracking issue for this is now https://github.com/ember-cli/ember-cli/issues/6501. I'm closing this issue in favor of the linked one.
