### ISSUE TITLE
Doesn't seem to be linting my addon or app dirs in an ember addon

### ISSUE THREAD

**Issue by Bockit** [ember-cli/ember-cli-eslint#142]
I'm using `ember-cli-eslint` in an addon, and I'm noticing it's not generating tests for files in the addon's `app/` or `addon` folders. There are tests every test in `tests/`.

```
ember-cli: 2.8.0
node: 6.2.2
os: darwin x64
```

package.json looks like this:

```json
{
    "devDependencies": {
    "active-model-adapter": "2.1.1",
    "bower": "1.7.7",
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-cli": "2.8.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-eslint": "3.0.0",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-mirage": "0.1.14",
    "ember-cli-moment-shim": "2.2.1",
    "ember-cli-qunit": "^2.1.0",
    "ember-cli-release": "0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.8.0",
    "ember-disable-prototype-extensions": "^1.1.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-lodash": "0.0.11",
    "ember-moment": "7.0.2",
    "ember-resolver": "^2.0.3",
    "ember-sinon": "0.5.1",
    "ember-sinon-qunit": "1.3.5",
    "loader.js": "4.0.7"
  },
  "keywords": [
    "ember-addon"
  ],
  "dependencies": {
    "ember-cli-babel": "^5.1.6",
    "ember-cli-htmlbars": "^1.0.3"
  },
}
```

Happy to provide more information, just let me know. If this is the wrong repo I'd appreciate a pointer to the right place.

Thanks for your time.

**Comment by rwjblue** [comment]
Can you provid a reproduction repo? It'll make it a lot easier to track down if we can clone and test locally...

**Comment by Bockit** [comment]
Will do

**Comment by Bockit** [comment]
Ok, I have more info now. It has something to do with the isDevelopingAddon method.

I've made a repro case available here: https://github.com/Bockit/ember-eslint-test fresh 2.8 addon generated and had `ember-cli-eslint@3`.

3 variations of index.js

This runs lint on addon/* files
```
module.exports = {
  name: 'eslint-test',
};
```

This does not run lint on addon/* files
```
module.exports = {
  name: 'eslint-test',

  isDevelopingAddon() {
    return false
  }
};
```

This runs lint on addon/* files
```
module.exports = {
  name: 'eslint-test',

  isDevelopingAddon() {
    return true
  }
};
```

Defined and returning false does not run lint on addon files. Interestingly, in no scenarios is lint run on app files.

1. I'm surprised that it doesn't work as expected when isDevelopingAddon is defined as returning false.
2. I'm a little surprised that under no circumstances are app files linted.

It's quite possible this is expected behaviour and I don't understand what's meant to be going on though.

PS: Sorry for the poor info in the original posting.

**Comment by rwjblue** [comment]
> Defined and returning false does not run lint on addon files.

Hehe, this is working as designed. 😛 

> Interestingly, in no scenarios is lint run on app files.

Yes, because `app/` files by definition are "owned" by the consuming app. This is just a bug that we haven't had time to fix yet.

> I'm surprised that it doesn't work as expected when isDevelopingAddon is defined as returning false.

Again, this is one of the purposes of this flag. `isDevelopingAddon` is `true` by default when you are running `ember test` / `ember serve`  / `ember build` / etc directly inside the addon's repo (i.e. not in a consuming app).  The point here, is that addons with JSHint failures **should not** fail app tests.

**Comment by Bockit** [comment]
> It's quite possible this is expected behaviour and I don't understand what's meant to be going on 

Yep!

That makes a lot of sense. Now I understand more what's going on with isDevelopingAddon, so thanks for the explanation.

> Yes, because `app/` files by definition are "owned" by the consuming app. This is just a bug that we haven't had time to fix yet.

If you already have an issue for tracking this, I'm happy to close this one.

**Comment by BrianSipple** [comment]
@rwjblue @Bockit I just encountered the same issue and realized I was making the same mistake with `isDevelopingAddon`. Thanks for walking through this 😄!
