### ISSUE TITLE
Merge all Linting into a single test

### ISSUE THREAD

**Issue by vvohra** [ember-cli/ember-cli-eslint#146]
We have a large amount of files in our Ember App. Because every file is turned into a test this is causing some things some issues:

- Majority of the log output is "ESLint - XYZ: should pass ESLint"
- Majority of test results are also Eslint errors
- Ember test Server becomes a pain to use because the select box is majority Eslint errors

What about having linting be one test? And the output of the test should be the files that have failed.

This might be what the ticket creator wanted #119.

**Comment by Turbo87** [comment]
@vvohra the reason this hasn't been done is that it would impact the performance of the build in a negative way, thought I don't know *how* big that impact will be. I've been thinking about this in the past but the https://github.com/stefanpenner/broccoli-persistent-filter that `broccoli-lint-eslint` is based on only allows for 1:1 mappings of files, so this would be a rather big change, which is the reason why I haven't started that yet.
