### ISSUE TITLE
Addon's index.js is not linted

### ISSUE THREAD

**Issue by jeffjewiss** [ember-cli/ember-cli-eslint#154]
I'm using `ember-cli-eslint` to lint my addon and for the most part it works great. Today I noticed that it's not actually linting the addon's `index.js` file. My editor is also setup to use eslint, which displayed warnings, which aren't present when running `ember test`.

Could this be due to how the broccoli trees are setup and the typical use case is to lint the `app` and `addon` directories (frontend Ember code), but not the addon build files?

**Comment by Turbo87** [comment]
> Could this be due to how the broccoli trees are setup and the typical use case is to lint the app and addon directories (frontend Ember code), but not the addon build files?

@jeffjewiss yes, that is correct. I'm not sure that there is much we can do about it. I usually install `eslint` as an explicit dev dependency and add a `lint` task to the `package.json` which is triggered by the CI system.

**Comment by jeffjewiss** [comment]
@Turbo87 thanks for clarifying! I'm fine with setting up a separate lint task as you described for handling this case.

Do you think it would be useful to add something to the readme detailing that these files won't be linted? Otherwise, I'm happy to close the issue.Thanks!

**Comment by Turbo87** [comment]
> Do you think it would be useful to add something to the readme detailing that these files won't be linted? Otherwise, I'm happy to close the issue.Thanks!

yeah, that might be a good idea. do you want to work on a PR for that?

**Comment by jeffjewiss** [comment]
@Turbo87 yeah, sounds good, I'll write something up.
