### ISSUE TITLE
Uint8Array (and other typed array) support question...

### ISSUE THREAD

**Issue by OakBehringer** [ember-cli/ember-cli-eslint#219]
```
module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module'
  },
  extends: 'eslint:recommended',
  env: {
    browser: true
  },
  rules: {
  }
};
```
...and then...

`let uInt8Array = new Uint8Array(5);`

...results in 

`  81:26  error  'Uint8Array' is not defined  no-undef`

Uint8Array is defined in the 2017 spec:

https://www.ecma-international.org/ecma-262/8.0/index.html#sec-intro

Guidance?  Thanks!
Adam

**Comment by Turbo87** [comment]
what you are looking for is 
```
env: {
  browser: true,
  es6: true,
}
```

(see https://github.com/sindresorhus/globals/blob/master/globals.json#L153)
