### ISSUE TITLE
disable automatic execution during ember test and ember serve

### ISSUE THREAD

**Issue by sarbbottam** [ember-cli/ember-cli-eslint#333]
I understand that the purpose of ember-cli-eslint to run automatically.

I am wondering if there is a way to control this behavior.

Like, run ember-cli-eslint automatically only if there is certain ENVIRONMENT_VARIABLE or maybe write a custom script.

I am wondering if that is possible. Google search did not provide me any pointer.

**Comment by Turbo87** [comment]
you could probably do something roughly like this:
```js
let blacklist = [];
if (process.env.ENVIRONMENT_VARIABLE) {
  blacklist.push('ember-cli-eslint');
}

let app = new EmberApp(defaults, {
  addons: { blacklist },
});
```

**Comment by sarbbottam** [comment]
Thank you so much @Turbo87. This is exactly what I was looking for.

Best!
Sarbbottam
