### ISSUE TITLE
GitHub releases do not match npm releases (specifically v5.1.0)

### ISSUE THREAD

**Issue by gorner** [ember-cli/ember-cli-eslint#411]
There is a v5.1.0 [published on NPM](https://www.npmjs.com/package/ember-cli-eslint) but that release is not reflected in the GitHub releases or tags. In fact the master branch package.json still lists version 5.0.0.

Asking out of an abundance of caution since I can't easily tell what's changed between v5.0.0 and v5.1.0.

**Comment by gorner** [comment]
Found a compare tool, changes seem to be minor: https://diff.intrinsic.com/ember-cli-eslint/5.0.0/5.1.0

**Comment by Horsed** [comment]
Hi! I have to archive the sources of any open-source library I use and cannot do so for v5.1.0.

**Comment by olegstepura** [comment]
Hi, @gorner ! Can we have a new release with this included https://github.com/ember-cli/ember-cli-eslint/commit/8c5dd1206f5ae727ae29923ae98bf0747e6b0ea5 please?

**Comment by gorner** [comment]
@olegstepura Hi, unfortunately I don’t maintain this package. I’m just an Ember app developer like you (I assume). Only a maintainer like @Turbo87 or @rwjblue can issue releases, if and when they have time. 

As your concern is different from mine, you may have it addressed more quickly if you open a separate issue yourself.

**Comment by olegstepura** [comment]
Ah, sorry, I was confused by label `author` here. True, you are author of this issue 🤦 . It's friday...

My concern is different, yes, I was trying to get rid of npm security warnings and wanted to update this package. But there was no release after https://github.com/ember-cli/ember-cli-eslint/commit/8c5dd1206f5ae727ae29923ae98bf0747e6b0ea5 

Let's see if they will not react here (since you pinged both maintainers).

**Comment by Turbo87** [comment]
whoops, thanks for pinging me @gorner. it looks like I forgot to push the tag to GitHub when I did the release. should be fixed now :)

**Comment by Turbo87** [comment]
> Can we have a new release with this included [8c5dd12](https://github.com/ember-cli/ember-cli-eslint/commit/8c5dd1206f5ae727ae29923ae98bf0747e6b0ea5) please?

@olegstepura since that is a semver-compatible update there is no need for a new release. you just have to update your lockfile if you used one.

**Comment by olegstepura** [comment]
Thanks, @Turbo87 ! Will regenerate `package-lock.json` then.
