### ISSUE TITLE
Support eslint 6

### ISSUE THREAD

**Issue by burritoIand** [ember-cli/ember-cli-eslint#460]
Greetings, just checking if we'll get a release with support for eslint 6 soon?

https://github.com/ember-cli/broccoli-lint-eslint/releases/tag/v6.0.0

**Comment by Al10s** [comment]
It would be nice indeed, I spent some time figuring out why I had a ton of lint errors while launching `ember serve`, while I had none while running `eslint`.
It turns out I declared eslint 6.x rules in my .eslintrc, and those rules are not understood by the current version of `ember-cli-eslint`.
So instead of checking my files, the following error is returned for each one of them :
```
  1:1  error  Definition for rule 'function-call-argument-newline' was not found  function-call-argument-newline
```

**Comment by nightire** [comment]
ember-cli-eslint really needs an upgrade to support eslint 6, eslint@7 is coming now.

**Comment by rwjblue** [comment]
FYI - we (the ember-cli team) think the right path forward here is to use `eslint` directly (not ember-cli-eslint/broccoli-lint-eslint). We are working towards making that the default (see https://github.com/ember-cli/ember-cli/pull/9009), but you can update your projects to use this structure already.

**Comment by burritoIand** [comment]
ok great @rwjblue thanks!

**Comment by cloke** [comment]
Does this mean support will never come? I would like lint to still run on file save and ember cli says to install this plugin to return that feature, but it then appears this plugin does not work if I have eslint 6/7 installed. It will give an error about the config file: ``` - Unexpected top-level property "overrides[0].extends".``` inside of .eslintrs.js

**Comment by jdurand** [comment]
@cloke as a workaround you should be able to get this working with eslint@7.23 by forcing the resolution for eslint & broccoli-lint-eslint. This worked for me: 
```javascript
{
  //...
  "resolutions": {
    "broccoli-lint-eslint/**/eslint": "^7.23.0",
    "ember-cli-eslint/**/broccoli-lint-eslint": "^6.0.0",
  }
}
```
