### ISSUE TITLE
eslint-config-ember not found

### ISSUE THREAD

**Issue by optikalefx** [ember-cli/ember-cli-eslint#48]
After installation I get this error

```
Error: Cannot read config package: eslint-config-ember Error: Cannot find module 'eslint-config-ember' 
```

Not sure what's up there.

**Comment by BrianSipple** [comment]
I haven't been able to replicate this after installing `ember-cli-eslint` into a newly generated ember app. Could you provide the steps that lead to this error -- or was this something to occurred upon running `ember install ember-cli-eslint` itself?

**Comment by optikalefx** [comment]
Yea, Ill work on isolating the conditions needed for the error.

**Comment by optikalefx** [comment]
Maybe this is an atom issue. But my steps were

```
$ ember new eslint-test
$ cd eslint-test
$ ember install ember-cli-eslint
$ atom .

Then I get this error in atom on any js file. 
![image](https://cloud.githubusercontent.com/assets/926885/14355032/9cb79bf6-fcad-11e5-8bc2-4172e8dfa228.png)

**Comment by optikalefx** [comment]
but eslint works fine without this plugin, it's only with this plugin do I get this error

**Comment by BrianSipple** [comment]
Very interesting. Possibly related: https://github.com/atom/atom/issues/8891

**Comment by optikalefx** [comment]
Atom is up to date, eslint wasn't but updating that didn't help.   I wonder why it would say that 'eslint-config-ember' isnt' found though

**Comment by jonathansamines** [comment]
Hey @optikalefx this has happened me before. The reason is because the `linter-eslint` plugin for atom, uses it´s "shipped" eslint version if you don´t have `eslint` directly installed locally (See https://github.com/AtomLinter/linter-eslint#installation). In that case the linter is unable to look for the sharable config alias.

In ember projects, when you are using npm@2, you are likely to run into this problem, since you are using `ember-cli-eslint` you are not likely to have eslint directly installed into `node_modules` because of that.

**Comment by optikalefx** [comment]
@jonathanKingston what do you recommend, installing a local eslint for the project?

**Comment by jonathanKingston** [comment]
@optikalefx use VIM :wink:

@BrianSipple do you think it would make sense to add in a dev dependency into the Ember project at the same time as `eslint-config-ember`, that sounds like it will solve Atom missing the dependency and be cleaner in a npm@2 world anyway.

**Comment by optikalefx** [comment]
heh, nice try. #emacsforever. Let me see if that package fixes it, and then I'd say yes, atom has become quite popular

**Comment by jcano** [comment]
I was getting the same problem with Sublime Text and it's a problem with where the editor linter looks for the config libraries. In my case, I installed eslint globally (`npm -g eslint`) and Sublime Text is using that binary so installing eslint-config-ember globally (`npm -g eslint-config-ember`) solved the issue.

If AtomLinter ships with its own eslint, it would be a matter of installing eslint-config-ember on Atom's `node_modules`, or installing eslint and the config locally as @jonathansamines pointed out it's described on the AtomLinter readme.
