### ISSUE TITLE
move into "ember-cli" org

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-eslint#50]
I'd like to propose moving this repo (and `broccoli-lint-eslint`) into the `ember-cli` GitHub org to make them more "official" since ESLint is the decided way in which we're moving forward.

@jonathanKingston would you be okay with that move?

/cc @rwjblue @BrianSipple

**Comment by jonathanKingston** [comment]
Makes little difference to me so long as there is some form of recognition to the initial work, if it widens adoption then I am fine with this.

**Comment by Turbo87** [comment]
@jonathanKingston we will certainly make sure to credit you as the original author! at the moment your name is mentioned in the `package.json` and in the license text in the Readme file and I would like to keep it that way. is there anywhere else where you'd like to be mentioned?

**Comment by Turbo87** [comment]
@jonathanKingston we've just invited you into the `ember-cli` org. once you accept you should be able to move the projects into it in the project settings.

/cc @nathanhammond @BrianSipple

**Comment by jonathanKingston** [comment]
Done @Turbo87 :+1:  - license is fine, my point was more around I'm happy for that to change also if there is a distinct number of contributors etc. In this case I'd just like a mention as the first author.

**Comment by Turbo87** [comment]
@jonathanKingston awesome, thanks!
