### ISSUE TITLE
Disabling linting for tests

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli-eslint#57]
Any tips on how to disable linting for tests?

I want to fix my app lint errors first, but the test lint errors drown everything out.

**Comment by BrianSipple** [comment]
In the options hash that you pass to the EmberApp constructor in `ember-cli-build.js`, there's a property called `hinting` that toggles linting. You could try setting it according to whether or not the app is running in a testing environment:

```

const env = process.env.EMBER_ENV;
const isTesting = env === 'test';

module.exports = function(defaults) {
  const app = new EmberApp(defaults, {    
    hinting: !isTesting
  });

  ....

});
```

**Comment by knownasilya** [comment]
I'm trying to disable hinting for the test files, not for all files when in test mode. Basically when I build I get the hinting errors from the `tests/*` dir, which I want to ignore.

**Comment by rwjblue** [comment]
I would think that adding an `tests/.eslintrc.js` file would give you the flexibility that you need.

**Comment by knownasilya** [comment]
Is there an option to not run any rules, or do I just remove the extends and put in a blank rules hash?

**Comment by rwjblue** [comment]
@knownasilya - I am unsure, I haven't tried what you are doing.  A quick search of eslint.org turns up this: http://eslint.org/docs/user-guide/command-line-interface#ignoring-files-from-linting

Maybe that will help...

**Comment by knownasilya** [comment]
Ah, totally forgot about that file, i.e. `.eslintignore` (for anyone else wondering).
