### ISSUE TITLE
QUnit tests fail on warnings

### ISSUE THREAD

**Issue by jwlawrence** [ember-cli/ember-cli-eslint#66]
When setting rules to warn ("1") any offending lines count as failed tests when running "ember test".  I tend to think that warnings should count as passing results when running tests in ember.

For me warnings are useful when running linters in text editors, providing suggestions to devs that aren't necessarily enforced, but considered good practice. Their usefulness while running tests in ember is debatable, but it would be nice to at least have the option to count them as passing rather than failing results.

Currently, I have to either relax all warning rules to ignore rules to pass tests and deploy my product or fix a couple hundred lines of code that have warnings. Thoughts?

**Comment by rwjblue** [comment]
I agree. We should fix this. 

The fix would be to make https://github.com/ember-cli/ember-cli-eslint/blob/master/index.js#L35 smarter about warn/error.

**Comment by BrianSipple** [comment]
Full agreement here as well! 

There's been an [ongoing discussion about this in `broccoli-lint-eslint`](https://github.com/ember-cli/broccoli-lint-eslint/issues/10), and it's possible that we could make refinements across both projects (in the case of `broccoli-lint-eslint`, determining the structure of the `errors` that get sent to the test generator callback). I could definitely look into this in the near future.
