### ISSUE TITLE
eslint --fix support

### ISSUE THREAD

**Issue by vasa-chi** [ember-cli/ember-cli-eslint#70]
Is there any way to enable eslint autofix?

**Comment by rwjblue** [comment]
Yes

    .node_modules/.bin/eslint --fix

**Comment by vasa-chi** [comment]
I know how to do that by hand:)
What I mean, is there any way to apply eslint fix from within ember-cli-eslint.

Sorry, I'm still learning ember ecosystem :) My experience is with webpack, where eslint-loader can do that (https://github.com/MoOx/eslint-loader#fix-default-false).

**Comment by rwjblue** [comment]
No, there is no way to do this with ember-cli-eslint, and I'm not keen on adding support. The eslint command line does a great job, we should not get in its way...

**Comment by vasa-chi** [comment]
OK. Thanks :)

**Comment by Turbo87** [comment]
> No, there is no way to do this with ember-cli-eslint, and I'm not keen on adding support. The eslint command line does a great job, we should not get in its way...

actually it should be reasonably easy to call `eslint --fix` from Ember CLI in a custom command provided by this addon

**Comment by alexlafroscia** [comment]
@Turbo87 like an `ember lint:fix`? #92 is proposing an `ember lint` so that might make sense.

**Comment by Turbo87** [comment]
yes, for example, although I tend to agree with @rwjblue that we should make sure `eslint --fix` also works properly with our default configs

**Comment by Turbo87** [comment]
since https://github.com/ember-cli/ember-cli-eslint/issues/70#issuecomment-225026667 works pretty well an could be turned into an npm script like `npm run eslint:fix` I don't think adding the complexity into this Ember addon would make sense.

since https://github.com/ember-cli/broccoli-lint-eslint/pull/49 was closed I'll close this issue now too.

**Comment by BlueRaja** [comment]
It actually doesn't work pretty well.  In fact if you try it, you'll get an error message saying the syntax is invalid.

**Comment by Samsinite** [comment]
Yeah, for me this doesn't work at all either:
```
$ npx eslint --fix app/
npx: installed 125 in 5.581s
Failed to load plugin ember: Cannot find module 'eslint-plugin-ember'
```

**Comment by Samsinite** [comment]
I'll give that a try, thanks!

**Comment by Samsinite** [comment]
That worked, just none of the newer ember violations could automatically be fixed :). That's okay, we created issues to clean up all of the new violations from the version upgrade.
