### ISSUE TITLE
Minimum builderFeatures required error

### ISSUE THREAD

**Issue by CarlosV89** [ember-cli/ember-cli-eslint#73]
I installed ember-cli-eslint on an existing proyect, when I try to ember server or ember run, I get this error message: 
`Minimum builderFeatures required: { persistentOutputFlag: true }`

Any clue as to why this is happening? I can't seem to find any information on this.

**Comment by CarlosV89** [comment]
We changed this in your plugin and it seemed to fix it. 

`index.js`
```
// eslint-disable-next-line no-underscore-dangle
  var nodeInfo = inputNode.__broccoliGetInfo__({
    persistentOutputFlag: true,
    sourceDirectories: true
  });

```

**Comment by CarlosV89** [comment]
https://github.com/ember-cli/broccoli-lint-eslint/blob/master/lib/index.js#L66

Adding the persistentOutputFlag here worked for us, we will either for that or try to send a PR to the author asking why this is getting throwed

**Comment by alexlafroscia** [comment]
Hey @CarlosV89, this is likely a problem with [`broccoli-lint-eslint`](https://github.com/ember-cli/broccoli-lint-eslint/issues/39), not this repo.  Are you OK with us closing this issue in favor of continuing the investigation in the issue on that repo instead?

**Comment by CarlosV89** [comment]
Yessir. Sry to have bothered you!

**Comment by alexlafroscia** [comment]
No bother at all, don't think that! Just hoping to combine the issues since a solution will come from `broccoli-lint-eslint` and there's already an issue over there.

Thanks for reporting!
