### ISSUE TITLE
uninstall ember-cli-jshint and install ember-cli-eslint cause an error

### ISSUE THREAD

**Issue by maxkoryukov** [ember-cli/ember-cli-eslint#78]
*from http://stackoverflow.com/q/37931556/1115187*

I want to use **eslint** instead of **jshint** in ember app. So, I just follow instructions from [**ember-cli-eslint** github page](https://github.com/ember-cli/ember-cli-eslint#ember-cli--250), and run this two commands:

    npm uninstall --save-dev ember-cli-jshint
    ember install ember-cli-eslint

And!!!! my project turns into a pumpkin: no one `ember` command doesn't work, throwing an error:

    Error: Cannot find module 'ember-try-config'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/projects/ember-demo/node_modules/ember-cli/node_modules/ember-try/lib/utils/config.js:7:34)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

----

Here is my environment:

    host@user $ ember --version
    Could not start watchman; falling back to NodeWatcher for file system events.
    Visit http://ember-cli.com/user-guide/#watchman for more info.
    ember-cli: 2.6.2
    node: 5.11.1
    os: linux x64

And I am working around **out of the box** project, just created with `ember new demo-ember`

**UPD**: if you will skip the uninstall step - you won't get a pumpkin)) in this case `ember` continues to work as expected, but I still couldn't use **eslint** as a linter tool.

**Comment by rwjblue** [comment]
Seems like a bad `node_modules` state. Though I'm unsure why these two specific addons would cause it.

**Comment by maxkoryukov** [comment]
@rwjblue, here is my current working solution:

1. create new ember app
2. run `ember install ember-cli-eslint`
3. remove **ember-cli-jshint** from `package.json`
4. remove `./.jshintrc` and `./tests/.jshintrc`
5. remove local node modules `rm -rm ./node_modules`
6. reinstall node modules: `npm install`
7. **DONE!**

If there are no other solutions - you could close the ticket, or I will close it in 2-3 days;)

**Comment by maxkoryukov** [comment]
I tried to reproduce, and this sequence got 5 of 5 fails.

**Comment by TameBadger** [comment]
same here

**Comment by maxkoryukov** [comment]
Looks, like it is not a bug of `ember-cli-eslint` , because the same result I have got with `ember-welcome-page`

```
npm uninstall --save-dev ember-welcome-page
```

**Comment by maxkoryukov** [comment]
Move issue to `ember-cli` repo:

ember-cli/ember-cli#6016
