### ISSUE TITLE
Automatically uninstall JSHint

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-cli-eslint#85]
Would uninstalling the JSHint addon and removing the config files after installation be desirable?  I noticed that `ember-cli-mocha` removed QUnit automatically, which is pretty nice... It would be nice to do the same in cleaning up the JSHint stuff, assuming one wouldn't want both installed on their machine.

I'm happy to implement this if it's something people agree we should do.

**Comment by BrianSipple** [comment]
There would definitely be a way to do that.  

I really like the idea of removing `ember-cli-jshint` -- that would just be `removePackageFromProject` inside the `afterInstall` hook -- but I'd be a bit concerned about the extra step of zapping user files. Those can be precious! Perhaps only doing the uninstall and them keeping the instructions in the README about tending to your JSHint files would be the best compromise.

**Comment by alexlafroscia** [comment]
Makes sense to me! I'll put a PR together 😄

**Comment by Turbo87** [comment]
> but I'd be a bit concerned about the extra step of zapping user files

there are several options for that:

- do nothing about it 😞 
- delete every files that looks remotely like `.jshintrc` 😞 
- tell the user he should manually delete all remaining `.jshintrc` files 😐 
- show a list of found `.jshintrc` files to the user and ask him if the addon should remove them for him 😍

**Comment by alexlafroscia** [comment]
That's a great idea! Would you want one "yes/no" or a prompt for each?

**Comment by Turbo87** [comment]
Maybe "yes/no/ask for each" initially but it think yes/no once should be enough too

**Comment by alexlafroscia** [comment]
@Turbo87 @rwjblue do you know how to test that these hooks work correctly?  Would it run if I do

```bash
$ npm install alexlafroscia/ember-cli-eslint#whatever
```

Or better yet, it there a way to trigger these hooks with an addon that you have installed locally and are using `npm link` on?

**Comment by Turbo87** [comment]
do you mean `ember generate ember-cli-eslint`?

**Comment by alexlafroscia** [comment]
Ahh, yup. Hadn't even thought of that, that's exactly what I needed.

**Comment by ro0gr** [comment]
Looks like I'm too late to the party. But shouldn't it be a responsibility of `ember-cli-jshint` addon to destroy its stuff? 
Though I'm not sure if it's technically possible to call blueprint `destroy` from another blueprint's `postInstall` hook.

**Comment by madeeha-khan** [comment]
> > but I'd be a bit concerned about the extra step of zapping user files
> 
> there are several options for that:
> 
> * do nothing about it disappointed
> * delete every files that looks remotely like `.jshintrc` disappointed
> * tell the user he should manually delete all remaining `.jshintrc` files neutral_face
> * show a list of found `.jshintrc` files to the user and ask him if the addon should remove them for him heart_eyes
> 
> obviously all of that should only happen if `.jshintrc` files were found

If you have installed using some package like npm, you can uninstall it by executing `npm remove -g jshint`
