### ISSUE TITLE
RFC: add `lint` command

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-eslint#92]
This would run the linting without running the tests.

**Comment by alexlafroscia** [comment]
Just something like `ember lint`? I'd be happy to look into putting that together tonight.

In the meantime I added the following to my `package.json` for the same effect:

```json
{
  "scripts": {
    "lint": "ember test --filter 'ESLint"
  }
}
```

Which builds the projects and then just lints the `app` and `tests` directories.

**Comment by kellyselden** [comment]
Sounds good.

**Comment by rwjblue** [comment]
`ember lint` seems good to me.

**Comment by Turbo87** [comment]
closing due to the discussion in https://github.com/ember-cli/ember-cli-eslint/pull/93#issuecomment-310931415
